apiVersion: v1
kind: Namespace
metadata:
  name: kuma-demo
  labels:
    kuma.io/sidecar-injection: enabled
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  namespace: kuma-demo
spec:
  selector:
    matchLabels:
      app: demo-app
  replicas: 1
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
        - name: demo-app
          image: "dennyherbrich/kuma-demo-counter:v15"
          env:
            - name: REDIS_HOST
              value: "redis_kuma-demo_svc_6379.mesh"
            - name: REDIS_PORT
              value: "80"
            - name: APP_VERSION
              value: "1.0"
            - name: APP_COLOR
              value: "#efefef"
          ports:
            - name: http
              containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: demo-app
  namespace: kuma-demo
  labels:
    # we use this label to have this service picked up for global hostname generation
    with-global-name: "true"
spec:
  selector:
    app: demo-app
  ports:
    - protocol: TCP
      appProtocol: http
      port: 5000
      targetPort: 5000
